image: docker:latest

stages:
  - build-ui
  - deploy-ui

build-ui:
  stage: build-ui
  image: node:dubnium
  before_script:
    - cd ./cloud-storage-ui
  script:
    - yarn install
    - yarn test
    - yarn build
  artifacts:
    paths:
      - build/
    expire_in: 20 mins
  environment:
    name: production
  only:
    - master

deploy-ui:
  stage: deploy-ui
  image: node:dubnium
  before_script:
    - cd ./cloud-storage-ui
  dependencies:
    - build-ui
  script:
    - yarn global add firebase-tools
    - firebase use --token $FIREBASE_TOKEN signed-sealed-delivered
    - firebase deploy --only hosting --token $FIREBASE_TOKEN
  environment:
    name: production
  only:
    - master
