image: docker:latest

stages:
  - build-ui
  - deploy-ui

build-ui:
  stage: build-ui
  image: node:dubnium
  before_script:
    - cd ./cloud-storage-ui
  script:
    - yarn install
    - yarn test
    - yarn build
  artifacts:
    paths:
      - cloud-storage-ui/build/
    expire_in: 20 mins
  environment:
    name: production
  only:
    - master

deploy-ui:
  stage: deploy-ui
  image: node:dubnium
  before_script:
    - cd ./cloud-storage-ui
    - yarn global add firebase-tools
  dependencies:
    - build-ui
  script:
    # run firebase init in the ./cloud-storage-ui directory
    - firebase use --token $FIREBASE_TOKEN signed-urls-beta
    - firebase deploy --only hosting --token $FIREBASE_TOKEN
  environment:
    name: production
  only:
    - master
